### ISSUE TITLE
Suggestion for additional sensors

### ISSUE THREAD

**Issue by menaibluey** [cabberley/HA_AemoNemData#5]
Hi, thanks for your great effort. Really appreciate it. If have a few questions and suggestions.

1. How does this differ from OpenNEM? One difference I can see is the polling interval which seems random in OpenNEM.
2. I've created a rudimentary integration inspired by someone from the Amber forum by using the https://visualisations.aemo.com.au/aemo/apps/api/report/ELEC_NEM_SUMMARY REST API and extracting some data to create my sensors. Obviously I prefer your custom component and would be very interested in adding some more sensors like these (I've attached a response JSON payload):

- SETTLEMENTDATE
- TOTALDEMAND
- PRICE_STATUS

Not sure whether there's any other interesting data points in that response.

[ELEC_NEM_SUMMARY.json](https://github.com/user-attachments/files/16257852/ELEC_NEM_SUMMARY.json)

Again, thanks heaps for your effort, much appreciated.

**Comment by cabberley** [comment]
So mine is totally different to opennem. They are retrieving and processing the generated data files that AEMO and require an intermediary system to transpose and present them as RestAPI. So timing wise of data for Opennem is dependant on several things. This one checks every 15 seconds adjustable during the 30-90 seconds after the 5min periods roll over, for the dashboard 
I took a similar approach to you, I retrieve a few of the datasets that populate the nem dashboard. Including the one that you have been using.

With your ask
1. The current 5min price should be the same as the price in your JSON. 2. By default that is firm as it is the actual. Not sure if when a market cap is breached if they retrospectively change a price, but the maths if they are doing it right they should know before they publish the firm price it got capped and reduced.
3. The settlement date is the 5min period time at the end of the current interval. 
4. Easy enough to add a sensor for the load in the next updates. 

Adding the loads is where things get interesting, because that number needs context, the first layer of which is the scheduled and semi scheduled. The second layer is the interchange and the demand being pushed or pulled there. Then with the interconnectors limits is that causing pressures. Then what does the loads and generation look like for the other end of the interconnectors.

So where do you stop in unravelling that data to make informed decisions/guesstimates on what is likely to happen?

Also, don't forget the market participants have another layer of data around market depth which the public can't see or get. Which is data that goes into the forecast pricing that Amber Energy generates.

Having said all of that I will look to add the load, generation and interconnect values in an update.

**Comment by menaibluey** [comment]
Thanks for your response. All makes sense and it's a great learning exercise to learn how that market operates. 

One other suggestion would be to come up with a sensor and a configurable formula to calculate an estimated household price. Given that the wholesale price is only about 30% to 40% it's obviously not what the consumer will be charged. So an option could be either a percentage, a fixed price or a combination of both to be added to the wholesale price. This would be a really helpful way to see how the wholesale price translates to an estimated household price. Does that make sense?

**Comment by cabberley** [comment]
That's a totally different ball game. 
Most energy providers are pushing (sometimes by stealth) ToU and Demand tariffs.
Each state has one or more energy distributors. That can have different network rates off-peak, shoulder and peak, which get added onto the spot price. Demand has a flat network rate during the day, but then takes the max 30min kWh usage found in the month between 6-9 pm and multiple that by a factor to create an additional cost for the month. So one bad 30min period in 30 days gets applied to everyday of the month.

Having said that, I use Amber and do have some other automations that calculate my 30min cost and then a total for the day and month which is fairly accurate. Day and month includes my daily network charges.

**Comment by menaibluey** [comment]
Yep, fully understand. This goes well beyond the purpose of this component. It's no issue for me to add that capability using a Helper template for my own purpose with my specific numbers and rates. 

Once I switch to Amber when I hopefully get my batteries I might ping you for your automation. I always try to keep these retailers honest with my own calculations.

**Comment by cabberley** [comment]
@menaibluey just released an updated integration which surfaces all the power flow sensors you were asking for.
